"""empty message

Revision ID: 11be7ba17435
Revises: 27f9878461f0
Create Date: 2022-02-21 13:06:20.844460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11be7ba17435'
down_revision = '27f9878461f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('release_date', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_column('release_date')

    # ### end Alembic commands ###
