"""empty message

Revision ID: 5ab27106a06f
Revises: 2fe7cc71c5af
Create Date: 2022-02-19 17:11:26.866512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ab27106a06f'
down_revision = '2fe7cc71c5af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_coupons')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_alembic_tmp_coupons',
    sa.Column('code', sa.VARCHAR(length=15), nullable=False),
    sa.Column('amount', sa.FLOAT(), nullable=False),
    sa.Column('cid', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    # ### end Alembic commands ###
