"""empty message

Revision ID: 9ea722e66638
Revises: fab76ed21cf7
Create Date: 2022-02-14 23:22:43.784957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ea722e66638'
down_revision = 'fab76ed21cf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orderitems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('time', sa.String(length=255), nullable=True),
    sa.Column('coupon', sa.Integer(), nullable=True),
    sa.Column('refund_requested', sa.String(), nullable=True),
    sa.Column('refund_reason', sa.Text(), nullable=True),
    sa.Column('refund_granted', sa.String(), nullable=True),
    sa.Column('ref_code', sa.String(length=20), nullable=True),
    sa.Column('totalprice', sa.Float(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['coupon'], ['coupons.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('order_items')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_items',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('ticket', sa.INTEGER(), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATETIME(), nullable=False),
    sa.Column('time', sa.VARCHAR(length=255), nullable=True),
    sa.Column('coupon', sa.INTEGER(), nullable=True),
    sa.Column('refund_requested', sa.BOOLEAN(), nullable=True),
    sa.Column('refund_reason', sa.TEXT(), nullable=True),
    sa.Column('refund_granted', sa.BOOLEAN(), nullable=True),
    sa.Column('ref_code', sa.VARCHAR(length=20), nullable=True),
    sa.Column('totalprice', sa.FLOAT(), nullable=True),
    sa.Column('phone', sa.VARCHAR(length=20), nullable=True),
    sa.ForeignKeyConstraint(['coupon'], ['coupons.id'], ),
    sa.ForeignKeyConstraint(['ticket'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('orderitems')
    # ### end Alembic commands ###
