"""add tootal and number fields

Revision ID: fab76ed21cf7
Revises: 8949a8ceb0fa
Create Date: 2022-01-23 21:24:54.034391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fab76ed21cf7'
down_revision = '8949a8ceb0fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('totalprice', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_column('phone')
        batch_op.drop_column('totalprice')

    # ### end Alembic commands ###
